export const OrderListTab = (t: any) => {
  return [
    {
      id: 1,
      name: t("admin_shop.orders.list.status.all"),
      tab: "all",
    },
    {
      id: 2,
      name: t("admin_shop.orders.list.status.awaiting"),
      tab: "awaiting",
    },
    {
      id: 3,
      name: t("admin_shop.orders.list.status.processing"),
      tab: "processing",
    },
    {
      id: 4,
      name: t("admin_shop.orders.list.status.shipping"),
      tab: "shipping",
    },
    {
      id: 5,
      name: t("admin_shop.orders.list.status.delivered"),
      tab: "delivered",
    },
    {
      id: 6,
      name: t("admin_shop.orders.list.status.canceled"),
      tab: "canceled",
    },
  ];
};

export const OrderDataAdmin = [
  {
    id: 285849382,
    status: "Đang vận chuyển",
    status_slug: "shipping",
    dt: 135000,
    total_qty: 13,
    grand_total: 138000,
    operate_model: "Dropship - Nhà bán tự đóng gói, Tiki giao hàng",
    label_order: "X Chưa in phiếu",
    order_date: "12/08/2021  - 11:10:06",
    confirm_date: "12/08/2021  - 11:10:06",
    type: "cod",
    items: [
      {
        id: 1,
        category_name: "Đồng hồ 1",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 1",
        sale_price: 0,
        qty: 1,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop mạnh tiến",
            link: null,
            store_id: 1,
          },
        ],
      },
    ],
    shipping_address: [
      {
        id: 1,
        name: "Nguyễn Minh Tý",
        road: "Số 1 đường số 15",
        ward: "Phường An Khánh",
        district: "Quận Ninh Kiều",
        city: "Cần Thơ",
        country: "Việt Nam",
        telephone: "0915661392",
      },
    ],
    shipping: [
      {
        method_fee_text: 22000,
        method_text: "Giao trước 24h Thứ Năm, 24/08",
        method_name: "Giao tiết kiệm",
        delivery_name: "Tikinow Smart Logistics",
      },
    ],
  },
  {
    id: 283849383,
    status: "Đã hủy",
    status_slug: "canceled",
    dt: 135000,
    total_qty: 13,
    grand_total: 138000,
    operate_model: "FBT - Hàng lưu kho tiki",
    label_order: "X Chưa in phiếu",
    order_date: "12/08/2021  - 11:10:06",
    confirm_date: "12/08/2021  - 11:10:06",
    items: [
      {
        id: 2,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
      {
        id: 3,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
    ],
    shipping_address: [
      {
        id: 1,
        name: "Nguyễn Minh Tý",
        road: "Số 1 đường số 15",
        ward: "Phường An Khánh",
        district: "Quận Ninh Kiều",
        city: "Cần Thơ",
        country: "Việt Nam",
        telephone: "0915661392",
      },
    ],
    shipping: [
      {
        method_fee_text: 22000,
        method_text: "Giao trước 24h Thứ Năm, 24/08",
        method_name: "Giao tiết kiệm",
        delivery_name: "Tikinow Smart Logistics",
      },
    ],
  },
  {
    id: 282249383,
    status: "Chờ xác nhận",
    status_slug: "awaiting",
    dt: 135000,
    total_qty: 13,
    grand_total: 138000,
    operate_model: "FBT - Hàng lưu kho tiki",
    label_order: "X Chưa in phiếu",
    order_date: "12/08/2021  - 11:10:06",
    confirm_date: "12/08/2021  - 11:10:06",
    items: [
      {
        id: 2,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
      {
        id: 3,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
    ],
    shipping_address: [
      {
        id: 1,
        name: "Nguyễn Minh Tý",
        road: "Số 1 đường số 15",
        ward: "Phường An Khánh",
        district: "Quận Ninh Kiều",
        city: "Cần Thơ",
        country: "Việt Nam",
        telephone: "0915661392",
      },
    ],
    shipping: [
      {
        method_fee_text: 22000,
        method_text: "Giao trước 24h Thứ Năm, 24/08",
        method_name: "Giao tiết kiệm",
        delivery_name: "Tikinow Smart Logistics",
      },
    ],
  },
  {
    id: 219383,
    status: "Đang xử lý",
    status_slug: "processing",
    dt: 135000,
    total_qty: 13,
    grand_total: 138000,
    operate_model: "FBT - Hàng lưu kho tiki",
    label_order: "X Chưa in phiếu",
    order_date: "12/08/2021  - 11:10:06",
    confirm_date: "12/08/2021  - 11:10:06",
    items: [
      {
        id: 2,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
      {
        id: 3,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
    ],
    shipping_address: [
      {
        id: 1,
        name: "Nguyễn Minh Tý",
        road: "Số 1 đường số 15",
        ward: "Phường An Khánh",
        district: "Quận Ninh Kiều",
        city: "Cần Thơ",
        country: "Việt Nam",
        telephone: "0915661392",
      },
    ],
    shipping: [
      {
        method_fee_text: 22000,
        method_text: "Giao trước 24h Thứ Năm, 24/08",
        method_name: "Giao tiết kiệm",
        delivery_name: "Tikinow Smart Logistics",
      },
    ],
  },
  {
    id: 119383,
    status: "Đã giao hàng",
    status_slug: "delivered",
    dt: 135000,
    total_qty: 13,
    grand_total: 138000,
    operate_model: "FBT - Hàng lưu kho tiki",
    label_order: "X Chưa in phiếu",
    order_date: "12/08/2021  - 11:10:06",
    confirm_date: "12/08/2021  - 11:10:06",
    items: [
      {
        id: 2,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
      {
        id: 3,
        category_name: "Đồng hồ",
        product_id: 1,
        product_sku: 7180770726869,
        product_name: "Order 2 2",
        sale_price: 0,
        qty: 2,
        price: 69000,
        subtotal: 138000,
        discount: 0,
        grand_total: 138000,
        thumbnail_url:
          "https://salt.tikicdn.com/cache/200x200/ts/product/4d/07/69/fee34463b2c954eb24ef46604cbe6b8e.png",
        current_seller: [
          {
            id: 1,
            name: "Shop ty",
            link: null,
            store_id: 1,
          },
        ],
      },
    ],
    shipping_address: [
      {
        id: 1,
        name: "Nguyễn Minh Tý",
        road: "Số 1 đường số 15",
        ward: "Phường An Khánh",
        district: "Quận Ninh Kiều",
        city: "Cần Thơ",
        country: "Việt Nam",
        telephone: "0915661392",
      },
    ],
    shipping: [
      {
        method_fee_text: 22000,
        method_text: "Giao trước 24h Thứ Năm, 24/08",
        method_name: "Giao tiết kiệm",
        delivery_name: "Tikinow Smart Logistics",
      },
    ],
  },
];
