export const VoucherTab = (t: any) => {
  return [
    {
      id: 1,
      name: t("user.voucher.all"),
      tab: "all",
    },
    {
      id: 2,
      name: `Tiki`,
      tab: "tiki",
    },
    {
      id: 3,
      name: t("user.voucher.shop"),
      tab: "nha-ban",
    },
    {
      id: 4,
      name: t("user.voucher.payment-offer"),
      tab: "uu-dai-nha-ban",
    },
    {
      id: 5,
      name: t("user.voucher.expire"),
      tab: "het-hieu-luc",
    },
  ];
};

export const VoucherData = [
  {
    id: 1,
    label: "Giảm 15K",
    seller_name: null,
    tags: [],
    status: "tiki",
    out_of_stock: false,
    coupon_id: 66855699,
    web_url: null,
    coupon_code: "KEHDGF",
    seller_id: 298886,
    payment: null,
    icon_name: "CAMERA",
    short_title: "Giảm 15K",
    period: "31/12/23",
    expired_at: 1703996519,
    simple_action: "cart_fixed",
    coupon_type: "SELLER_COUPON",
    discount_amount: 15000,
    min_amount: 1999000,
    rule_id: 3092217,
    saved: false,
    discount_max: null,
    short_description: "Cho đơn hàng từ 2 triệu",
    icon_url: "https://vcdn.tikicdn.com/cache/128x128/ts/seller/37/d3/2c/b6e0da6f3fe1bf5fde5bdb592cbbce7b.jpg",
    app_url: null,
  },
  {
    id: 2,
    label: "Giảm 15K",
    seller_name: null,
    tags: [],
    status: "nha-ban",
    out_of_stock: false,
    coupon_id: 66855627,
    web_url: null,
    coupon_code: "NKM15K",
    // long_description: "Giảm 15K cho đơn hàng từ 2 triệu.\nÁp dụng cho sản phẩm của CAMERA PHƯƠNG ĐÔNG Store.\nMỗi khách hàng được sử dụng tối đa 1 lần.",
    url: "https://tiki.vn/cua-hang/camera-phuong-dong-store",
    seller_id: 298886,
    payment: null,
    icon_name: "CAMERA ",
    short_title: "Giảm 15K",
    period: "31/12/23",
    expired_at: 1703996519,
    simple_action: "cart_fixed",
    coupon_type: "SELLER_COUPON",
    discount_amount: 15000,
    min_amount: 4999000,
    rule_id: 3092217,
    saved: false,
    discount_max: null,
    short_description: "Cho đơn hàng từ 2 triệu",
    icon_url: "https://vcdn.tikicdn.com/cache/128x128/ts/seller/37/d3/2c/b6e0da6f3fe1bf5fde5bdb592cbbce7b.jpg",
    app_url: null,
  },
  {
    id: 3,
    label: "Giảm 15K",
    seller_name: null,
    tags: [],
    status: "het-hieu-luc",
    out_of_stock: false,
    coupon_id: 66855444,
    web_url: null,
    coupon_code: "GYHTHG",
    // long_description: "Giảm 15K cho đơn hàng từ 2 triệu.\nÁp dụng cho sản phẩm của CAMERA PHƯƠNG ĐÔNG Store.\nMỗi khách hàng được sử dụng tối đa 1 lần.",
    url: "https://tiki.vn/cua-hang/camera-phuong-dong-store",
    seller_id: 298886,
    payment: null,
    icon_name: "ĐÔNG",
    short_title: "Giảm 15K",
    period: "31/12/23",
    expired_at: 1703996519,
    simple_action: "cart_fixed",
    coupon_type: "SELLER_COUPON",
    discount_amount: 15000,
    min_amount: 1999000,
    rule_id: 3092217,
    saved: false,
    discount_max: null,
    short_description: "Cho đơn hàng từ 2 triệu",
    icon_url: "https://vcdn.tikicdn.com/cache/128x128/ts/seller/37/d3/2c/b6e0da6f3fe1bf5fde5bdb592cbbce7b.jpg",
    app_url: null,
  },
];
