export const SupplierData = [
  {
    id: 1,
    supplier_code: "10ABX01",
    name: "NutiFood",
    phone: "0394748177",
    email: "anpkpc04434@fpt.edu.vn",
    tag: ["supplier", "supplier", "fdsfds"],
    address: "Ninh Kiều, Cần Thơ",
    website: "https://www.nike.com/vn/",
  },
  {
    id: 2,
    supplier_code: "10ABX99",
    name: "NutiFood 2",
    phone: "0394748179",
    email: "anpkpc04434@gmail.com",
    tag: ["fdsf", "ytutuy", "nnnnn"],
    address: "Ninh Kiều 2, Cần Thơ",
    website: "https://onlinemart.edu.vn",
  },
  {
    id: 3,
    supplier_code: "10ABX50",
    name: "Jungcook",
    phone: "0394748189",
    email: "anpkpc04434@education.vn",
    tag: ["aaaaaaa", "cccccc", "nnvvvnnn"],
    address: "Ninh Kiều 3, Cần Thơ",
    website: "onlinemart.vn",
  },
];
